### ISSUE TITLE
Strange data parsing errors

### ISSUE THREAD

**Issue by kaiwei** [cewood/csv2beancount#2]
For the life of me, I can't get the convertor to work and keep running into the below errors although I don't think there is anything wrong with the config. Any hints or suggestions would be greatly appreciated!

> WARN[0000]/$HOME/.go/pkg/mod/github.com/cewood/csv2beancount@v1.0.0/internal/main.go:242 github.com/cewood/csv2beancount/internal.formatRecord() error parsing date                            config.Csv.DateLayoutIn= error="parsing time \"17 Dec,Total outstanding balance,,1,087.31\": extra text: \"17 Dec,Total outstanding balance,,1,087.31\"" record[config.Csv.Date]="17 Dec,Total outstanding balance,,1,087.31"
> ;; []string{"17 Dec,Total outstanding balance,,1,087.31"}
> 0001-01-01 * "17 Dec,Total outstanding balance,,1,087.31" "17 Dec,Total outstanding balance,,1,087.31"
>   Expenses:Unknown  -17 Dec,Total outstanding balance,,1,087.31
>   Assets:Unknown   17 Dec,Total outstanding balance,,1,087.31

[config.txt](https://github.com/cewood/csv2beancount/files/10531471/config.txt)
[mart.csv](https://github.com/cewood/csv2beancount/files/10531469/mart.csv)

**Comment by cewood** [comment]
Hey :wave: 

> error parsing date config.Csv.DateLayoutIn= error="parsing time "

That's where your error is, the date you used in your date format isn't in the correct format, both the date in and out formats.

I'll have to do a better job of explaining the date formats in the config. The date you use to specify them, it has to be the same one you can see in the example [here](https://github.com/cewood/csv2beancount#example). This is a Go thing, it's a well known date, that lets the compiler know what each digit represents, so there isn't any room for ambiguity. That's why in the example, you can see the same date expressed in two different formats.

Looking at your input file, the date format there doesn't match what you've described in your config. You'll need to fix that, or csv2beancount won't be able to parse the records.

Hope this helps.
